build:
  cuda_version: "12.1.1"
  system_packages:
    - "libssl-dev"
    - "libx11-6"
    - "libxext6"
    - "libgl1-mesa-glx"
  python_packages:
    - "diffusers==0.24.0"
    - "pandas==2.1.4"
    - "torch==2.1.0"
    - "transformers==4.36.1"
    - "accelerate==0.25.0"
